[package]
name = "bip39-hash-checker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
digest = "0.10.3"
sha2 = "0.10.2"
itertools = "0.10.3"
